1|Actualizar la Shell|setup|pkg install git -y && pkg install python python3 -y && pkg install pip pip3 -y && pkg install curl -y && apt update && apt upgrade -y|bash alhack.sh
2|Phishing Tool|zphisher|bash zphisher.sh|bash zphisher.sh
3|WebCam Hack|CamPhish|bash camphish.sh|bash camphish.sh
4|Subscan|subscan|chmod +x subscan|./subscan
5|Gmail Bomber|fast-mail-bomber|mv config.example.php config.php && php index.php update-providers && rm -rf data/nodes.json data/dead_providers.json && sleep 4 && php index.php update-nodes && php index.php refine-nodes|php index.php start-bombing
6|DDOS Attack|DDoS-Ripper|::|python3 DRipper.py
7|CiLocks|CiLocks|sudo apt update -y && sudo apt install php nodejs npm adb scrcpy wget unzip apktool jq -y && chmod +x cilocks|sudo bash cilocks
9|Ip Info|track-ip|bash trackip|bash trackip
10|Dorks-eye|dorks-eye|pip install -r requirements.txt|python3 dorks-eye.py
11|HackerPro|hackerpro|apt update && apt upgrade && apt install git && apt install python2 && sudo bash install.sh|python2 hackerpro.py
12|RED_HAWK|RED_HAWK|::|php rhawk.php
13|VirusCrafter|TigerVirus|apt update && apt upgrade -y && pkg install git -y|bash app.sh
14|Info-Site|info-site|pkg install curl -y && pkg install git -y|bash info.sh
15|BadMod|BadMod|sudo apt-get update && sudo apt-get install php && sudo apt-get install php-curl && chmod u+x INSTALL && chmod u+x BadMod.php|sudo php BadMod.php
16|Facebash|facebash|bash install.sh && chmod +x facebash.sh && tor|sudo ./facebash.sh
17|DARKARMY|DARKARMY|pkg install git && pkg install python2 && apt install git && apt install python2 && chmod +x darkarmy.py|python2 darkarmy.py
18|AUTO-IP-CHANGER|Auto_Tor_IP_changer|sudo apt-get install tor && pip3 install requests && sleep 8 && python3 install.py|python3 install.py